### ISSUE TITLE
Preselected periods doesn't support two-way binding

### ISSUE THREAD

**Issue by spanitz** [doroppu/yoso-datepicker#2]
It'll be more convenient if the preselected periods can be submitted by selected-period.list. In that case we can benefit from two-way-binding.

**Comment by lukas-zech-software** [comment]
Should two way binding be introduced for cost of the dependecy on gfke-period in the hosting app?

see #7

**Comment by lukas-zech-software** [comment]
obsolete due to filterSttingsService introduced in 4.0.0
