### ISSUE TITLE
templateUrl wrong?

### ISSUE THREAD

**Issue by Schnueggel** [doroppu/yoso-datepicker#3]
yosoDatePickerDirective.js uses templateUrl:

  templateUrl: 'common/directives/yosoDatePickerDirectiveTemplate.html'

is this the intention or should this not be:

template: require('./yosoDatePickerDirectiveTemplate.html')

**Comment by lukas-zech-software** [comment]
Yep, you're right, this is outrageously wrong!!!

The responsible developer should be flailed and flogged!
