### ISSUE TITLE
ng-mouseleave="cancelSelecting()" in selector-container

### ISSUE THREAD

**Issue by Schnueggel** [doroppu/yoso-datepicker#6]
If possible

ng-mouseleave="cancelSelecting()" should be added to yoso-datepicker__selector-container

```html
 <div class="yoso-datepicker__selector-container" ng-class="{'visible': isSelecting}">
```

at the moment its only on yoso-datepicker__date-selector

```html
        <div class="yoso-datepicker__date-selector"
             ng-mouseleave="cancelSelecting()">
```

**Comment by lukas-zech-software** [comment]
Doing so would not call __cancelSelecting__ when the user moves the pointer from the **yoso-datepicker__date-selector** to the **yoso-datepicker__period-selector** which would cause erroneous behaviour when changing the period mode while selecting.

If necessary the call to  __cancelSelecting__ could additionally be applied on mouseleave on **yoso-datepicker__selector-container**

In which scenario is the current solution not working? Leaving **yoso-datepicker__selector-container** should also always include leaving **yoso-datepicker__date-selector** as it is a child element of it?

**Comment by Schnueggel** [comment]
When you move with the mouse from the date-selector to the date-period the container is vanishing. Because isSelecting will be set to false
