### ISSUE TITLE
Display dates in reverse order

### ISSUE THREAD

**Issue by spanitz** [doroppu/yoso-datepicker#8]
I'm wondering if it is much more convenient to select dates from a reverse order (means latest first: 2015-04-30., 2015-04-29.,... 2015-04-01., 2015-03-31,...) in some cases. Especially if you're going to select dates from the perspective of the past instead of the future. So an additional display mode (lets say "reverse") could be enabled.

**Comment by lukas-zech-software** [comment]
There is already a option implemented to reverse the order of the dates.
It was missing in the documentation.
I just updated the ReadMe with the parameter

See (here)[https://github.com/doroppu/yoso-datepicker#order-dates-ascending-optionaldefaultfalse]

**Comment by spanitz** [comment]
nice
